behaviors:
  SurvivalAgent:
    trainer_type: ppo
    max_steps: 2_000_000
    time_horizon: 64
    summary_freq: 10_000
    batch_size: 512
    buffer_size: 20480
    learning_rate: 3.0e-4
    beta: 5.0e-4
    epsilon: 0.2
    lambd: 0.95
    num_epoch: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
